### ISSUE TITLE
"level":"error","ts":1596025413.503453"

### ISSUE THREAD

**Issue by sramek5** [redhat-cop/cert-utils-operator#65] opened 2020-07-29 12:41 UTC
I am not sure if I can use this tool separately from operator-sdk.

However, after deploying with helm, I get **Back-off restarting failed container** error.
Logs:
{"level":"error","ts":1596025413.503453,"logger":"cmd","msg":"","error":"no such file or directory","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/home/travis/gopath/src/github.com/redhat-cop/cert-utils-operator/cmd/manager/main.go:146\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.linux.amd64/src/runtime/proc.go:203"}

What should I do about that?

**Comment by raffaelespazzoli** [comment] 2020-07-29 13:03
@mathianasj would you mind looking into this issue?

**Comment by mathianasj** [comment] 2020-07-29 13:15
I will take a look

**Comment by mathianasj** [comment] 2020-07-29 16:16
@sramek5 can you provide some more details about where you are deploying

Kubernetes version, openshift version

I was unable to duplicate on a 4.5 openshift cluster is why I ask.

**Comment by sramek5** [comment] 2020-07-30 08:27
Hi @mathianasj, thank you for helping me.

Versions:
Helm - v3.2.4
Kubernetes: Client - v1.18.6.
                      Server - v1.18.4
Cert-utils-operator - v0.2.1

**Comment by mathianasj** [comment] 2020-07-31 13:51
@sramek5 I was able to find the root cause of the issue, this was due to not checking if the operator was running on an OpenShift implementation.  I have created a pull request to resolve the issue and will work to get it merged.  Thank you for reporting this.

**Closed** 2020-07-31 14:17 UTC
Labels: bug
